In [1]:
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import numpy as np
import struct
import sys
from array import array
import itertools
import os
import sys
from scipy import signal
from scipy.optimize import curve_fit
pi = np.pi
clight = 299792458

In [7]:
IbDC = 2.5
QL = 4e4
RoQ = 73
Rsh = RoQ*QL
phis = 81.23/180*pi
Vtot = 2.26e6
f0 = 78e3
h = 7560
frf = f0*h

In [12]:
tgphi = 2*IbDC*Rsh*np.sin(phis)/Vtot

In [13]:
df = tgphi/(2*QL)*frf
print(df)

47061.2319867


In [15]:
(0.51e6)**2/(2*73*135486.6909537)

13148.943536630211

In [54]:
Vs = np.zeros(2)
Vq = np.zeros(2)
Vnew = 3.4e6 # per cavity
PhisPhasor = 83.9/180*pi
VnewD = 0.51e6
PhisPhasorD = -83.9/180*pi
Vs[0] = Vnew*np.cos(PhisPhasor)
Vq[0] = Vnew*np.sin(PhisPhasor)
Vs[1] = VnewD*np.cos(PhisPhasorD)
Vq[1] = VnewD*np.sin(PhisPhasorD)
Vreftot = np.sqrt(Vs**2+Vq**2) 
thetaL = np.array([-77.43,82.28])/180.0*pi #np.array([-77.43,82.28])/180.0*pi  # angle between Ig and Vc
IbDC = 2.5
QL = np.array([8.7659e4,1.3148e4])
Rsh = np.array([73,73])*QL
Vbr = 2*IbDC*Rsh
PhisPhasor = np.arctan(Vq/Vs)
tgPhi = -(Vbr*np.sin(PhisPhasor)/Vreftot+(1+Vbr*np.cos(PhisPhasor)/Vreftot)*np.tan(thetaL))

In [55]:
tgPhi

array([-0.38765734, -5.39643759])

In [53]:
Vbr*np.sin(PhisPhasor)/Vreftot

array([ 9.35716897, -9.35656408])

In [49]:
(1+Vbr*np.cos(PhisPhasor)/Vreftot)*np.tan(thetaL)

array([-18.7144045 ,  14.75300167])

In [50]:
np.tan(thetaL)

array([-9.35723553,  7.3767655 ])